routes/web.php
<?php

use App\Http\Controllers\ProductCategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("home");
Route::resource('products', ProductController::class);
Route::resource('variants', VariantController::class);
Route::resource('category', ProductCategoryController::class);

app/Models/Variant.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Variant extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'size'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/VariantController.php
<?php

namespace App\Http\Controllers;

use App\Models\Variant;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\StoreVariantRequest;
use App\Http\Requests\UpdateVariantRequest;

class VariantController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $variants = Variant::paginate(5);
        return view('variants.index', compact('variants'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreVariantRequest $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
            'size' => 'required|string',
        ]);

        if ($validator->fails()) {
            return redirect()->route('variants.index')->withErrors($validator)->withInput();
        }

        Variant::create($request->all());

        return redirect()->route('variants.index')->with('success', 'Variant created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Variant $variant)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Variant $variant)
    {
        // 
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateVariantRequest $request, Variant $variant)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
            'size' => 'required|string',
        ]);

        if ($validator->fails()) {
            return redirect()->route('variants.index', $variant)->withErrors($validator)->withInput();
        }

        $variant->update($request->all());

        return redirect()->route('variants.index')->with('success', 'Variant updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Variant $variant)
    {
        $variant->delete();

        return redirect()->route('variants.index')->with('success', 'Variant deleted successfully');
    }
}

resources/views/variants/index.blade.php
@extends('layouts.app')
@section('title', 'Variants')
@section('header', 'Kelola Variant')
@section('content')
    {{-- Form isi variant --}}
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-8">
                    @if (session('success'))
                        <div class="bg-green-500 text-white p-4 mb-4">
                            {{ session('success') }}
                        </div>
                    @endif

                    @if (session('error'))
                        <div class="bg-red-500 text-white p-4 mb-4">
                            {{ session('error') }}
                        </div>
                    @endif
                    <h2 class="text-xl font-semibold mb-4" id="formTitle">Form Tambah Kategori Product</h2>
                    <form action="{{ route('variants.store') }}" method="POST" id="variantForm">
                        @csrf
                        <input type="hidden" id="variantId" name="variantId" value="">
                        <div class="mb-4">
                            <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Nama Variant : </label>
                            <input type="text" id="name" name="name"
                                class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500"
                                value="" placeholder="Masukkan nama variant">
                        </div>
                        <div class="mb-4">
                            <label for="size" class="block text-gray-700 text-sm font-bold mb-2">Ukuran Variant :
                            </label>
                            <input type="text" id="size" name="size"
                                class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500"
                                value="" placeholder="Masukkan Ukuran (S/L/XL dll)">
                        </div>
                        <button type="submit"
                            class="bg-red-500 hover:bg-red-600 text-white font-medium py-2 px-4 rounded-md"
                            id="submitButton">Simpan Data</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{-- Table Variant --}}
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <div class="p-4">
                    <h2 class="text-xl font-semibold mb-4">Daftar Variants</h2>
                    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                        <table class="w-full text-sm text-left">
                            <thead class="text-xs bg-indigo-500 text-white">
                                <tr>
                                    <th scope="col" class="px-6 py-3">
                                        ID
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Nama Variant
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Ukuran Variant
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($variants as $index => $variant)
                                    <tr
                                        class="{{ $index % 2 === 0 ? 'bg-gray-100' : 'bg-white' }} border-b hover:bg-gray-200">
                                        <td class="px-6 py-4">
                                            {{ $variant->id }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ $variant->name }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ $variant->size }}
                                        </td>
                                        <td class="px-6 py-4">
                                            <button type="button"
                                                onclick="editVariant('{{ $variant->id }}',
                                                '{{ $variant->name }}', '{{ $variant->size }}')"
                                                class="text-blue-500 hover:text-blue-700">Edit</button>
                                            <form action="{{ route('variants.destroy', $variant) }}"
                                                onclick="return confirmDelete()" method="POST" class="inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="text-red-500 hover:text-red-700">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                @if ($variants->isEmpty())
                                    <tr>
                                        <td colspan="10" class="px-6 py-4 text-center text-gray-500">
                                            No data found.
                                        </td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                        {{ $variants->links() }}
                    </div>

                    <!-- Additional messages or warnings -->
                </div>
            </div>
        </div>
    </div>

    {{-- Script --}}
    <script>
        function editVariant(id, name, size) {
            document.getElementById('name').value = name;
            document.getElementById('size').value = size;
            document.getElementById('variantId').value = id;
            document.getElementById('formTitle').innerText = 'Ubah Variant';
            document.getElementById('submitButton').innerText = 'Ubah Variant';
            // Setelah mengisi formulir, atur metode formulir menjadi PUT
            document.getElementById('variantForm').method = 'POST';
            document.getElementById('variantForm').action = '{{ route('variants.update', '') }}/' + id;

            // Tambahkan input tersembunyi untuk metode PUT
            var methodField = document.createElement('input');
            methodField.setAttribute('type', 'hidden');
            methodField.setAttribute('name', '_method');
            methodField.setAttribute('value', 'PUT');

            // Periksa apakah input _method sudah ada, jika ya, hapus
            var existingMethodField = document.getElementById('_method');
            if (existingMethodField) {
                existingMethodField.parentNode.removeChild(existingMethodField);
            }

            // Tambahkan input _method ke dalam formulir
            document.getElementById('variantForm').appendChild(methodField);
        }
    </script>
@endsection