routes/web.php
<?php

use App\Http\Controllers\ProductCategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("home");
Route::resource('products', ProductController::class);
Route::resource('variants', VariantController::class);
Route::resource('category', ProductCategoryController::class);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>@yield('title', 'Selamat Datang')</title>
    <style>
        .dynamic-bg {
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>

<body class="font-sans bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-white">

    <!-- Navbar -->
    @include('layouts.navbar')
    <!-- header -->
    <header class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                @yield('header')
            </h2>
        </div>
    </header>
    <!-- Content -->
    <div>
        @yield('content')
    </div>
    <!-- Footer -->
    @include('layouts.footer')
</body>

</html>

resources/views/layouts/footer.blade.php
<!-- Footer -->
<footer class="bg-gray-200 dark:bg-gray-700 py-8">
    <div class="container mx-auto text-center text-gray-600 dark:text-gray-300">
        <p>&copy; 2023 Laravel Shop. All rights reserved.</p>
    </div>
</footer>
<script>
    // Fungsi untuk mendapatkan gambar acak dari Unsplash
    async function getRandomImage() {
        const response = await fetch('https://source.unsplash.com/1600x900/?shopping');
        return response.url;
    }

    // Fungsi untuk mengatur latar belakang dengan gambar acak
    async function setRandomBackground() {
        const backgroundImage = await getRandomImage();
        document.getElementById('jumbotron-section').style.backgroundImage = `url('${backgroundImage}')`;
    }

    // Panggil fungsi setRandomBackground ketika halaman dimuat ulang
    window.addEventListener('load', setRandomBackground);
</script>

resources/views/layouts/navbar.blade.php
<nav class="bg-gray-900 text-white border-gray-200">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{{ route('home') }}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap">Flowbite</span>
        </a>
        <button data-collapse-toggle="navbar-default" type="button"
            class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
            aria-controls="navbar-default" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M1 1h15M1 7h15M1 13h15" />
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul
                class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-gray-900">
                <li>
                    <a href="{{ route('home') }}"
                        class="block py-2 px-3 {{ request()->routeIs('home') ? 'text-white bg-blue-700' : 'text-blue-700 bg-transparent' }}"
                        aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{{ route('products.index') }}"
                        class="block py-2 px-3 {{ request()->routeIs('products.*') ? 'text-white bg-blue-700' : 'text-blue-700 bg-transparent' }}"
                        aria-current="page">Products</a>
                </li>
                <li>
                    <a href="{{ route('variants.index') }}"
                        class="block py-2 px-3 {{ request()->routeIs('variants.*') ? 'text-white bg-blue-700' : 'text-blue-700 bg-transparent' }}"
                        aria-current="page">Variants</a>
                </li>
                <li>
                    <a href="{{ route('category.index') }}"
                        class="block py-2 px-3 {{ request()->routeIs('category.*') ? 'text-white bg-blue-700' : 'text-blue-700 bg-transparent' }}"
                        aria-current="page">Category</a>
                </li>
            </ul>
        </div>
    </div>
</nav>