routes/web.php
<?php

use App\Http\Controllers\ProductCategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("home");
Route::resource('products', ProductController::class);
Route::resource('variants', VariantController::class);
Route::resource('category', ProductCategoryController::class);

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Variant;
use App\Models\ProductImage;
use App\Models\ProductCategory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'description', 'price', 'stock', 'variant_id', 'category_id', 'image_id'];

    public function variant()
    {
        return $this->belongsTo(Variant::class);
    }

    public function category()
    {
        return $this->belongsTo(ProductCategory::class);
    }

    public function image()
    {
        return $this->hasOne(ProductImage::class);
    }
}

app/Models/ProductCategory.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class ProductCategory extends Model
{
    use HasFactory;
    protected $fillable = ['name'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductCategory;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\StoreProductCategoryRequest;
use App\Http\Requests\UpdateProductCategoryRequest;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $productcategories = ProductCategory::paginate(5);
        return view('products.product_category.index', compact('productcategories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreProductCategoryRequest $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
        ]);

        if ($validator->fails()) {
            return redirect()->route('category.index')->withErrors($validator)->withInput();
        }

        ProductCategory::create($request->all());

        return redirect()->route('category.index')->with('success', 'Variant created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(ProductCategory $productCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(ProductCategory $productCategory)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateProductCategoryRequest $request, ProductCategory $productCategory)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
            'size' => 'required|string',
        ]);

        if ($validator->fails()) {
            return redirect()->route('category.index', $productCategory)->withErrors($validator)->withInput();
        }

        $productCategory->update($request->all());

        return redirect()->route('category.index')->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(ProductCategory $category)
    {
        $category->delete();

        return redirect()->route('category.index')->with('success', 'Category deleted successfully');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Variant;
use Illuminate\Support\Str;
use App\Models\ProductImage;
use App\Models\ProductCategory;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $products = Product::paginate(5);
        $variants = Variant::all();
        $categories = ProductCategory::all();
        $images = ProductImage::all();
        return view('products.index', compact('products', 'variants', 'categories', 'images'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreProductRequest $request)
    {
        Validator::make($request->all(), [
            'name' => 'required|string',
            'description' => 'required|string',
            'price' => 'required|integer',
            'stock' => 'required|integer',
            'variant_id' => 'nullable|exists:variants,id',
            'category_id' => 'nullable|exists:product_categories,id',
            'url' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:5120', // 5 MB
        ]);

        try {
            $product = Product::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'price' => $request->input('price'),
                'stock' => $request->input('stock'),
                'variant_id' => $request->input('variant_id'),
                'category_id' => $request->input('category_id'),
            ]);

            if ($request->hasFile('image')) {
                $imagePath = $request->file('image')->store('product_images', 'public');
                ProductImage::create([
                    'product_id' => $product->id,
                    'product_image' => $imagePath,
                ]);
            }

            return redirect()->route('products.index')->with('success', 'Product created successfully');
        } catch (\Exception $e) {
            // Tangani kesalahan lainnya di sini, jika diperlukan
            return view('products.index')->with('error', 'Failed to create product. ' . $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        // Validate the request
        Validator::make($request->all(), [
            'productId' => 'required|exists:products,id',
            'name' => 'required|string',
            'description' => 'required|string',
            'price' => 'required|integer',
            'stock' => 'required|integer',
            'variant_id' => 'nullable|exists:variants,id',
            'category_id' => 'nullable|exists:product_categories,id',
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:5120', // 5 MB
        ]);

        // if ($validator->fails()) {
        //     return redirect()->route('products.index')->withErrors($validator)->withInput();
        // }

        // Find the product
        $product = Product::findOrFail($request->input('productId'));

        // Update the product
        $product->update([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'price' => $request->input('price'),
            'stock' => $request->input('stock'),
            'variant_id' => $request->input('variant_id'),
            'category_id' => $request->input('category_id'),
        ]);

        // Handle image upload
        if ($request->hasFile('image')) {
            // Delete the old image if it exists
            if ($product->image) {
                Storage::disk('public')->delete($product->image->product_image);
                $product->image->delete();
            }

            // Store the new image
            $imagePath = $request->file('image')->store('product_images', 'public');
            ProductImage::create([
                'product_id' => $product->id,
                'product_image' => $imagePath,
            ]);
        }

        return redirect()->route('products.index')->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        // Hapus gambar terkait
        if ($product->image) {
            Storage::disk('public')->delete($product->image->product_image);
            $product->image->delete();
        }

        // Hapus produk
        $product->delete();

        return redirect()->route('products.index')->with('success', 'Product deleted successfully');
    }
}

resources/views/products/product_category/index.blade.php
@extends('layouts.app')
@section('title', 'Category Product')
@section('header', 'Kelola Kategori')
@section('content')
    {{-- Form isi variant --}}
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-8">
                    @if (session('success'))
                        <div class="bg-green-500 text-white p-4 mb-4">
                            {{ session('success') }}
                        </div>
                    @endif

                    @if (session('error'))
                        <div class="bg-red-500 text-white p-4 mb-4">
                            {{ session('error') }}
                        </div>
                    @endif
                    <h2 class="text-xl font-semibold mb-4" id="formTitle">Form Tambah Kategori Product</h2>
                    <form action="{{ route('category.store') }}" method="POST" id="categoryForm">
                        @csrf
                        <input type="hidden" id="categoryId" name="categoryId" value="">
                        <div class="mb-4">
                            <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Nama Variant : </label>
                            <input type="text" id="name" name="name"
                                class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500"
                                value="" placeholder="Masukkan nama variant">
                        </div>
                        <button type="submit"
                            class="bg-red-500 hover:bg-red-600 text-white font-medium py-2 px-4 rounded-md"
                            id="submitButton">Simpan Data</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{-- Table Variant --}}
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-6">
                <div class="p-4">
                    <h2 class="text-xl font-semibold mb-4">Daftar Kategori Produk</h2>
                    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                        <table class="w-full text-sm text-left">
                            <thead class="text-xs bg-indigo-500 text-white">
                                <tr>
                                    <th scope="col" class="px-6 py-3">
                                        ID
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Nama Kategori
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($productcategories as $index => $category)
                                    <tr
                                        class="{{ $index % 2 === 0 ? 'bg-gray-100' : 'bg-white' }} border-b hover:bg-gray-200">
                                        <td class="px-6 py-4">
                                            {{ $category->id }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ $category->name }}
                                        </td>
                                        <td class="px-6 py-4">
                                            <button type="button"
                                                onclick="editVariant('{{ $category->id }}',
                                                '{{ $category->name }}')"
                                                class="text-blue-500 hover:text-blue-700">Edit</button>
                                            <form action="{{ route('category.destroy', $category) }}"
                                                onclick="return confirmDelete()" method="POST" class="inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit"
                                                    class="text-red-500 hover:text-red-700">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                @if ($productcategories->isEmpty())
                                    <tr>
                                        <td colspan="10" class="px-6 py-4 text-center text-gray-500">
                                            No data found.
                                        </td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                        {{ $productcategories->links() }}
                    </div>

                    <!-- Additional messages or warnings -->
                </div>
            </div>
        </div>
    </div>

    {{-- Script --}}
    <script>
        function editVariant(id, name, size) {
            document.getElementById('name').value = name;
            document.getElementById('size').value = size;
            document.getElementById('categoryId').value = id;
            document.getElementById('formTitle').innerText = 'Ubah Kategori';
            document.getElementById('submitButton').innerText = 'Ubah Kategori';
            // Setelah mengisi formulir, atur metode formulir menjadi PUT
            document.getElementById('categoryForm').method = 'POST';
            document.getElementById('categoryForm').action = '{{ route('variants.update', '') }}/' + id;

            // Tambahkan input tersembunyi untuk metode PUT
            var methodField = document.createElement('input');
            methodField.setAttribute('type', 'hidden');
            methodField.setAttribute('name', '_method');
            methodField.setAttribute('value', 'PUT');

            // Periksa apakah input _method sudah ada, jika ya, hapus
            var existingMethodField = document.getElementById('_method');
            if (existingMethodField) {
                existingMethodField.parentNode.removeChild(existingMethodField);
            }

            // Tambahkan input _method ke dalam formulir
            document.getElementById('categoryForm').appendChild(methodField);
        }
    </script>
@endsection